
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wsd-ecommerce-app-backend
    ports:
      - "8088:8080"
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  database:
    image: postgres:15
    container_name: wsd-ecommerce-postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - wsd-ecommerce-postgres-db-data:/var/lib/postgresql/data


volumes:
  wsd-ecommerce-postgres-db-data:
    name: wsd-ecommerce-postgres-db-data