INSERT INTO customers (id, name, email) VALUES
    (1,  'Alice Smith',    'alice.smith1@example.com'),
    (2,  'Bob Johnson',    'bob.johnson2@example.com'),
    (3,  'Charlie Brown',  'charlie.brown3@example.com'),
    (4,  'Diana Prince',   'diana.prince4@example.com'),
    (5,  'Ethan Hunt',     'ethan.hunt5@example.com'),
    (6,  'Fiona Gallagher','fiona.gallagher6@example.com'),
    (7,  'George Miller',  'george.miller7@example.com'),
    (8,  'Hannah Lee',     'hannah.lee8@example.com'),
    (9,  'Ivan Petrov',    'ivan.petrov9@example.com'),
    (10, 'Julia Kim',      'julia.kim10@example.com'),
    (11, 'Kevin Baker',    'kevin.baker11@example.com'),
    (12, 'Laura Chen',     'laura.chen12@example.com'),
    (13, 'Michael Scott',  'michael.scott13@example.com'),
    (14, 'Nina Hart',      'nina.hart14@example.com'),
    (15, 'Oscar Wilde',    'oscar.wilde15@example.com'),
    (16, 'Pam Beesly',     'pam.beesly16@example.com'),
    (17, 'Quentin Blake',  'quentin.blake17@example.com'),
    (18, 'Rachel Green',   'rachel.green18@example.com'),
    (19, 'Steve Rogers',   'steve.rogers19@example.com'),
    (20, 'Tina Turner',    'tina.turner20@example.com');
